# Generated by Django 4.0.4 on 2022-04-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(max_length=15, verbose_name='Credit Type')),
            ],
            options={
                'verbose_name': 'CreditType',
                'verbose_name_plural': 'CreditTypes',
            },
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_description', models.CharField(max_length=150, verbose_name='Credit Description')),
                ('min_payment', models.FloatField(verbose_name='Minimum Payment')),
                ('max_payment', models.FloatField(verbose_name='Maximun Payment')),
                ('credit_term', models.PositiveIntegerField(verbose_name='Credit Term')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_of_credit', models.ForeignKey(limit_choices_to={'allowed_credit': True}, on_delete=django.db.models.deletion.CASCADE, to='banks.bank', verbose_name='Bank of Credit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
            },
        ),
    ]
