# Generated by Django 4.0.4 on 2022-04-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittype',
            options={'verbose_name': 'Credit Type', 'verbose_name_plural': 'Credit Types'},
        ),
    ]
