# Generated by Django 4.0.4 on 2022-04-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_credits_max_payment_alter_credits_min_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credits.credittype', verbose_name='Credit Type'),
        ),
    ]
