# Generated by Django 4.0.4 on 2022-04-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktype',
            old_name='type',
            new_name='bank_type',
        ),
    ]
