# Generated by Django 4.0.4 on 2022-04-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_rename_type_banktype_bank_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktype',
            options={'verbose_name': 'Bank Type', 'verbose_name_plural': 'Bank Types'},
        ),
    ]
